### ISSUE TITLE
Emoji database already exists

### ISSUE THREAD

**Issue by JSGRD22** [neurokitti/ZenWorkspaceIcons#5]
https://github.com/github/gemoji/blob/master/db/emoji.json

Is there a reason to create our own version?

**Comment by StudioMovieGirl** [comment]
yes I want the community to be able to pick key words they would use. for example if i need an icon for school and i search school. I will get this:
![image](https://github.com/user-attachments/assets/b038665d-c587-4bd1-8dc2-3b35ef79fc67)

and that is usless when picking icons for workspaces. if i search for an icon for my english class i wouldnt get anything:
![image](https://github.com/user-attachments/assets/1c98153d-7247-4ec5-8df7-3cd0205d13d1)


by doing it this way the community can define what that they want will make this feature way better than any other browser.

in arc if a want a streaming space (eather for live streaming or netflix lol) I wont get anything.

![image](https://github.com/user-attachments/assets/2fa14784-d16d-456c-9c8d-9624e8dadd1b)

by doing it this way we take the user directly into acount

lol its the zen way

**Comment by StudioMovieGirl** [comment]
feel free to take keywords from other places though and add them.

**Comment by JSGRD22** [comment]
I see, that's a good point. Could still start from the generic emoji db and add on to it though. I'll add the generic tags when I'm free later if nobody does it first
